---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hollow-silverblue
description: A custom fedora atomic distro based on silverblue for my laptop
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

platforms:
  - linux/amd64

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - crashdummy/Displaylink

    install:
      packages:
        - fzf
        - zsh
        - ruby
        - ruby-devel
        - hyfetch
        - fastfetch
        - tailscale
        - gnome-firmware
        - mediawriter
        - cpu-x
        - brasero
        - displaylink
        - google-chrome-stable

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: script
    snippets:
      - systemctl enable tailscaled.service
      - systemctl enable displaylink.service
      - gem install colorls

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system

        remotes:
          - name: flathub
            url: https://dl.flathub.org/repo/flathub.flatpakrepo

          - name: fedora
            url: https://registry.fedoraproject.org
            type: oci
            gpg-verify: false

        install:
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - com.usebottles.bottles
          - org.gnome.Weather
          - org.gnome.TextEditor
          - org.gnome.NautilusPreviewer
          - org.gnome.Calculator
          - org.gnome.Characters
          - org.gnome.Contacts
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.Papers
          - org.gnome.baobab
          - org.gnome.Snapshot
          - org.gnome.font-viewer
          - org.gnome.clocks
          - org.gnome.Extensions

  - type: signing
